### PR TITLE
add goimports

### PR DESCRIPTION
**Pull request by bokunodev**
now, format and fix imports before save.

### CODE REVIEW

**Comment by rgieseke** [comment]
Thank you! I don't really use Go and am wondering whether this would error if `goimports` is not installed.

From reading this page - https://godoc.org/golang.org/x/tools/cmd/goimports - it seems this is also a replacement of `gofmt`.

**Comment by bokunodev** [comment]
no, ``goimports`` will be skipped if it is not installed.
already tested.

**Comment by rgieseke** [comment]
How about having

```lua
-- Default format command
M.format_command = "gofmt"
```

...

```lua
local p = io.popen(M.format_command..[[ 2>&1 << "EOL"
]]..text..[[
EOL
]])
```

and then in your `init.lua`:

```lua
_M["go"] = require("go")
_M["go"].format_command = "goimports"
```

That way the formatting call would only happen once and be flexible. Seems similar to what other editors do

https://michaelwhatcott.com/gosublime-goimports/

What do you think?

**Comment by bokunodev** [comment]
since `goimports` also detects syntax errors, yes it will be better.

**Comment by rgieseke** [comment]
Pushed in 5df402c3d952430e30b8e7a86657ecaaf8ebc1d4

Let me know if there are any issues with this approach!

**Comment by bokunodev** [comment]
I didn't do much `lua`.
but I think redirecting all output of `gofmt` or` goimports` command to a file then read it later is inefficient.
specifically with large code bases.
and both `gofmt` and `goimports` **only** detect syntax errors.

I think it would be better if we run `gofmt` or` goimport` with the `-w` option and ignore the entire output. then test the code with `go test`.
```Lua
-- change from FILE_BEFORE_SAVE to FILE_AFTER_SAVE
events.connect(events.FILE_AFTER_SAVE, function()
	if buffer:get_lexer() ~= 'go' then return end
	local gof = buffer.filename
        -- ignore the entire output
	local tmp = {io.popen(M.format_command..' -w '..gof):close()}
        -- reload file if any change
	if tmp[3] == 0 then buffer.reload() end
        -- do the test
	local p = io.popen('go test '..gof..' 2>&1')
	local out = p:read('*a')
	local status = {p:close()}
        -- if the test is success return immediately.
	if status[3] == 0 then return end
	local line, msg = out:match(':(%d-):%d-:([^\n]+)')
	line = tonumber(line)
	buffer.annotation_clear_all()
	buffer.annotation_visible = buffer.ANNOTATION_BOXED
	buffer.annotation_text[line] = msg
	buffer.annotation_style[line] = 9
end)
```

**Comment by bokunodev** [comment]
sorry for my poor english.

**Comment by rgieseke** [comment]
Hm, I think running `test` should rather be a separate command, this could also be slow for a large test-suite.

With Textadept this could work by calling the now event-based function with a shortcut

```lua
keys.go.ct = function()  -- Ctrl-t
   --- the testing code...
end
```

**Comment by bokunodev** [comment]
@rgieseke oh, yes. you are right.

```Lua
events.connect(events.FILE_AFTER_SAVE, function()
	if buffer:get_lexer() ~= 'go' then return end
	local file = buffer.filename
	local p = io.popen(M.format_command..' -w '..file..' 2>&1')
	local out = p:read('*a')
	local status = {p:close()}
	if status[3] == 0 then
		buffer.reload()
		return
	end
	local line, msg = out:match(':(%d-):%d-:([^\n]+)')
	line = tonumber(line)
	buffer.annotation_clear_all()
	buffer.annotation_visible = buffer.ANNOTATION_BOXED
	buffer.annotation_text[line] = msg
	buffer.annotation_style[line] = 6
end)
```

**Comment by rgieseke** [comment]
Not sure about changing the formatting logic, but happy to include a separate `test` function!

**Comment by bokunodev** [comment]
@rgieseke the`test` function is the hard part. because go work with package not individual file.
idont know how to get **package import path** from current opened file and how to deal with go module.
but [this is how i did.](https://github.com/bokunodev/textadept_modules/tree/master/modules/go)

**Comment by rgieseke** [comment]
Cool, thanks for sharing! I'd close this PR now, for my (admittedly very limited) usage of Go the current workflow with gofmt works well enough and we fixed the original issue of enabling goimports!

**Pull request closed without merging**
